version: '3.8'

services:
  app:
    build: .
    container_name: clinsys-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clinsys_os
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION: 86400000
    depends_on:
      - db
    networks:
      - clinsys-net

  db:
    image: postgres:15-alpine
    container_name: clinsys-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clinsys_os
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clinsys-net

  frontend:
    build: ./frontend
    container_name: clinsys-frontend
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - clinsys-net

networks:
  clinsys-net:
    driver: bridge

volumes:
  postgres_data:
