version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: clinsys-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clinsys_os
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clinsys-net

networks:
  clinsys-net:
    driver: bridge

volumes:
  postgres_data:
